import { useState } from "react";

const initialRows = [
  { aufgabe: "", rolle: "", kategorie: "", skill: "", soll: 1 }
];

const examplePrompt = "";

const teamMembers = ["Anna", "Ben", "Chris"];

export default function SkillMatrixSetup() {
  const [rows, setRows] = useState(initialRows);
  const [projectText, setProjectText] = useState(examplePrompt);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [skills, setSkills] = useState({});

  const handleChange = (index, field, value) => {
    const updated = [...rows];
    updated[index][field] = field === "soll" ? parseInt(value) || 1 : value;
    setRows(updated);
  };

  const handleSkillChange = (skillKey, member, value) => {
    setSkills({
      ...skills,
      [skillKey]: {
        ...skills[skillKey],
        [member]: parseInt(value) || 0
      }
    });
  };

  const addRow = () => {
    setRows([...rows, { aufgabe: "", rolle: "", kategorie: "", skill: "", soll: 1 }]);
  };

  const autoGenerateFromText = () => {
    const aiRows = [
      {
        aufgabe: "Insektenhotels konstruieren",
        rolle: "Bauleitung",
        kategorie: "Handwerk",
        skill: "Holzbearbeitung",
        soll: 3
      },
      {
        aufgabe: "Projekt dokumentieren",
        rolle: "Dokumentation",
        kategorie: "Kommunikation",
        skill: "Fotografie",
        soll: 2
      },
      {
        aufgabe: "Öffentlichkeitsarbeit planen",
        rolle: "PR",
        kategorie: "Marketing",
        skill: "Social Media",
        soll: 4
      }
    ];
    setRows(aiRows);
    setAutoGenerated(true);
  };

  const getColor = (soll, ist) => {
    if (ist === soll) return "bg-green-200";
    if (soll - ist === 1) return "bg-yellow-200";
    if (soll - ist >= 2) return "bg-red-200";
    return "";
  };

  return (
    <div className="p-4 space-y-6">
      <h1 className="text-xl font-bold">SkillMatrix NG</h1>

      <div className="space-y-2">
        <label className="block text-sm font-medium">Projektbeschreibung eingeben:</label>
        <textarea
          rows={6}
          value={projectText}
          onChange={(e) => setProjectText(e.target.value)}
          className="w-full p-2 border rounded"
          placeholder="Hier Projektbeschreibung eingeben..."
        />
        <button
          onClick={autoGenerateFromText}
          className="px-4 py-2 bg-green-600 text-white rounded"
        >
          Projektstruktur mit KI erzeugen
        </button>
      </div>

      <div className="space-y-2">
        <div className="grid grid-cols-5 gap-2 font-semibold">
          <div>Aufgabe</div>
          <div>Rolle</div>
          <div>Kategorie</div>
          <div>Skill</div>
          <div>Soll</div>
        </div>
        {rows.map((row, index) => (
          <div key={index} className="grid grid-cols-5 gap-2 items-center">
            <input type="text" placeholder="Aufgabe" value={row.aufgabe} onChange={(e) => handleChange(index, "aufgabe", e.target.value)} className="p-2 border rounded" />
            <input type="text" placeholder="Rolle" value={row.rolle} onChange={(e) => handleChange(index, "rolle", e.target.value)} className="p-2 border rounded" />
            <input type="text" placeholder="Kategorie" value={row.kategorie} onChange={(e) => handleChange(index, "kategorie", e.target.value)} className="p-2 border rounded" />
            <input type="text" placeholder="Skill" value={row.skill} onChange={(e) => handleChange(index, "skill", e.target.value)} className="p-2 border rounded" />
            <input type="number" min={1} max={4} value={row.soll} onChange={(e) => handleChange(index, "soll", e.target.value)} className="p-2 border rounded w-16" />
          </div>
        ))}
      </div>

      <h2 className="text-lg font-semibold pt-6">Team-Profile & Skill-Levels</h2>
      <div className="overflow-auto">
        <table className="min-w-full border text-sm">
          <thead>
            <tr>
              <th className="border px-2 py-1">Skill</th>
              <th className="border px-2 py-1">Soll</th>
              {teamMembers.map(name => (
                <th key={name} className="border px-2 py-1">{name}</th>
              ))}
            </tr>
          </thead>
          <tbody>
            {rows.map((row, i) => {
              const skillName = row.skill;
              const soll = row.soll;
              const skillLevels = skills[skillName] || {};
              const hasGap = teamMembers.every(member => (skillLevels[member] || 0) === 0);

              return (
                <tr key={i}>
                  <td className="border px-2 py-1">{skillName}</td>
                  <td className="border px-2 py-1 text-center">{soll}</td>
                  {teamMembers.map(member => {
                    const ist = skillLevels[member] || 0;
                    const defizit = ist < soll ? (soll - ist >= 2 ? "!" : "") : "";
                    const color = getColor(soll, ist);

                    return (
                      <td key={member} className={`border px-2 py-1 text-center ${color}`}>
                        <div className="relative">
                          <input
                            type="number"
                            min={0}
                            max={4}
                            value={ist}
                            onChange={(e) => handleSkillChange(skillName, member, e.target.value)}
                            className="w-12 text-center bg-transparent"
                          />
                          {defizit && (
                            <span className="absolute right-1 top-0 text-red-500 font-bold">{defizit}</span>
                          )}
                        </div>
                      </td>
                    );
                  })}
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>
    </div>
  );
}

